# PostgreSQL Connection
# spring.datasource.url=jdbc:postgresql://192.168.131.101:5432/photo_market
# Desplegamos en el mismo computador el programa y la base de datos 104M01
# spring.datasource.url=jdbc:postgresql://localhost:5432/photo_market
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.sarxzpyyryhhkubgeilz}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:VNPnbZawvsBUG2vv}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Inicialización de datos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
#spring.sql.init.mode=always
# Server port
server.port=8085